DROP TABLE kmdm_accounts CASCADE CONSTRAINTS;
DROP TABLE kmdm_account_status CASCADE CONSTRAINTS;
DROP TABLE kmdm_account_types CASCADE CONSTRAINTS;
DROP TABLE kmdm_permissions CASCADE CONSTRAINTS;
DROP TABLE kmdm_role_permissions CASCADE CONSTRAINTS;
DROP TABLE kmdm_roles CASCADE CONSTRAINTS;
DROP TABLE kmdm_user_accounts CASCADE CONSTRAINTS;
DROP TABLE kmdm_users CASCADE CONSTRAINTS;

CREATE TABLE kmdm_accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    balance NUMBER(38,2) NOT NULL,
    status NUMBER,
    type NUMBER,
    PRIMARY KEY(account_id)
);
-- account_status --
CREATE TABLE kmdm_account_status(
    status_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    status VARCHAR2(64) UNIQUE,
    PRIMARY KEY(status_id)
);

-- account_types --
CREATE TABLE kmdm_account_types(
    type_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    type VARCHAR2(64) UNIQUE,
    interest_rate NUMBER(38,2),
    monthly_fee NUMBER(38,2),
	permission_id NUMBER,
    PRIMARY KEY(type_id)
);

-- users --
CREATE TABLE kmdm_users(
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    username VARCHAR2(64) NOT NULL UNIQUE,
    user_pwd VARCHAR(64) NOT NULL,
    email VARCHAR2(64) NOT NULL UNIQUE,
    firstname VARCHAR2(64) NOT NULL,
    lastname VARCHAR2(64)  NOT NULL,
    role NUMBER,
    PRIMARY KEY(user_id)
);

-- roles --
CREATE TABLE kmdm_roles(
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
	name VARCHAR2(64) UNIQUE,
    PRIMARY KEY(role_id)
);

-- permissions --
-- I think I can put a UNIQUE constrint on the --
-- name column and remove it from the primary --
-- key here. --
CREATE TABLE kmdm_permissions (
    permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    permission_name VARCHAR2(64) NOT NULL UNIQUE,
    PRIMARY KEY(permission_id)
);
-- role_permissions --
CREATE TABLE kmdm_role_permissions (
    role_id NUMBER,
    permission_id NUMBER,
    PRIMARY KEY(role_id, permission_id)
);
-- user_accounts
CREATE TABLE kmdm_user_accounts(
    account_id NUMBER,
    user_id NUMBER,
    PRIMARY KEY(account_id, user_id)
);
-- constraints --
ALTER TABLE kmdm_accounts
    ADD CONSTRAINT fk_accounts_type FOREIGN KEY (type) REFERENCES kmdm_account_types(type_id);
ALTER TABLE kmdm_accounts
    ADD CONSTRAINT fk_accounts_status FOREIGN KEY (status) REFERENCES kmdm_account_status(status_id);
    
ALTER TABLE kmdm_account_types
	ADD CONSTRAINT fk_account_types_permissions FOREIGN KEY (permission_id) REFERENCES kmdm_permissions(permission_id);
                  
ALTER TABLE kmdm_users
ADD CONSTRAINT fk_users_role FOREIGN KEY (role) REFERENCES kmdm_roles(role_id);

ALTER TABLE kmdm_user_accounts
    ADD CONSTRAINT fk_user_accounts_account FOREIGN KEY (account_id) REFERENCES kmdm_accounts(account_id);
ALTER TABLE kmdm_user_accounts
    ADD CONSTRAINT fk_user_accounts_user FOREIGN KEY (user_id) REFERENCES kmdm_users(user_id);

ALTER TABLE kmdm_role_permissions
    ADD CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES kmdm_roles(role_id) ON DELETE CASCADE;
ALTER TABLE kmdm_role_permissions
    ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES kmdm_permissions(permission_id) ON DELETE CASCADE;
--
